/* tslint:disable */
/* eslint-disable */
/**
 * Eth Beacon Node API
 * API specification for the beacon node, which enables users to query and participate in Ethereum 2.0 phase 0 beacon chain.  All requests by default send and receive JSON, and as such should have either or both of the \"Content-Type: application/json\" and \"Accept: application/json\" headers.  In addition, some requests can return data in the SSZ format.  To indicate that SSZ data is required in response to a request the header \"Accept: application/octet-stream\" should be sent.  Note that only a subset of requests can respond with data in SSZ format; these are noted in each individual request.  API endpoints are individually versioned.  As such, there is no direct relationship between all v1 endpoints, all v2 endpoints, _etc._ and no such relationship should be inferred.  All JSON responses return the requested data under a `data` key in the top level of their response.  Additional metadata may or may not be present in other keys at the top level of the response, dependent on the endpoint.  The rules that require an increase in version number are as follows:    - no field that is listed in an endpoint shall be removed without an increase in the version number   - no field that is listed in an endpoint shall be altered in terms of format (_e.g._ from a string to an array) without an     increase in the version number  Note that it is possible for a field to be added to an endpoint's data or metadata without an increase in the version number. 
 *
 * OpenAPI spec version: v2.5.0 - Ethereum Proof-of-Stake Consensus Specification v1.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BeaconStateEth1Data } from './beacon-state-eth1-data';
import { BeaconStateFork } from './beacon-state-fork';
import { Ethv1beaconpoolattesterSlashingsAttestation1DataSource } from './ethv1beaconpoolattester-slashings-attestation1-data-source';
 /**
 * The [`BeaconState`](https://github.com/ethereum/consensus-specs/blob/v1.3.0/specs/phase0/beacon-chain.md#beaconblock) object from the CL spec.
 *
 * @export
 * @interface BeaconState
 */
export interface BeaconState {

    /**
     * @type {any}
     * @memberof BeaconState
     * @example 1
     */
    genesisTime: any;

    /**
     * @type {any}
     * @memberof BeaconState
     * @example 0xcf8e0d4e9587369b2301d0790347320302cc0943d5a1884560367e8208d920f2
     */
    genesisValidatorsRoot: any;

    /**
     * @type {any}
     * @memberof BeaconState
     * @example 1
     */
    slot: any;

    /**
     * @type {BeaconStateFork}
     * @memberof BeaconState
     */
    fork: BeaconStateFork;

    /**
     * The [`BeaconBlockHeader`](https://github.com/ethereum/consensus-specs/blob/v1.3.0/specs/phase0/beacon-chain.md#beaconblockheader) object from the CL spec.
     *
     * @type {any}
     * @memberof BeaconState
     */
    latestBlockHeader: any;

    /**
     * Fixed length of 8192 items
     *
     * @type {any}
     * @memberof BeaconState
     */
    blockRoots: any;

    /**
     * Fixed length of 8192 items
     *
     * @type {any}
     * @memberof BeaconState
     */
    stateRoots: any;

    /**
     * Variable length list, maximum 16777216 items
     *
     * @type {any}
     * @memberof BeaconState
     */
    historicalRoots: any;

    /**
     * @type {BeaconStateEth1Data}
     * @memberof BeaconState
     */
    eth1Data: BeaconStateEth1Data;

    /**
     * Fixed length of 1024 items
     *
     * @type {any}
     * @memberof BeaconState
     */
    eth1DataVotes: any;

    /**
     * @type {any}
     * @memberof BeaconState
     * @example 1
     */
    eth1DepositIndex: any;

    /**
     * Variable length list, maximum 1099511627776 items
     *
     * @type {any}
     * @memberof BeaconState
     */
    validators: any;

    /**
     * Validator balances in gwei. Variable length list, maximum 1099511627776 items
     *
     * @type {any}
     * @memberof BeaconState
     */
    balances: any;

    /**
     * Fixed length of 65536 items
     *
     * @type {any}
     * @memberof BeaconState
     */
    randaoMixes: any;

    /**
     * Per-epoch sums of slashed effective balances. Fixed length of 8192 items
     *
     * @type {any}
     * @memberof BeaconState
     */
    slashings: any;

    /**
     * @type {any}
     * @memberof BeaconState
     */
    previousEpochAttestations: any;

    /**
     * @type {any}
     * @memberof BeaconState
     */
    currentEpochAttestations: any;

    /**
     * Bit set for every recent justified epoch
     *
     * @type {any}
     * @memberof BeaconState
     * @example 0x01
     */
    justificationBits: any;

    /**
     * @type {Ethv1beaconpoolattesterSlashingsAttestation1DataSource}
     * @memberof BeaconState
     */
    previousJustifiedCheckpoint: Ethv1beaconpoolattesterSlashingsAttestation1DataSource;

    /**
     * @type {Ethv1beaconpoolattesterSlashingsAttestation1DataSource}
     * @memberof BeaconState
     */
    currentJustifiedCheckpoint: Ethv1beaconpoolattesterSlashingsAttestation1DataSource;

    /**
     * @type {Ethv1beaconpoolattesterSlashingsAttestation1DataSource}
     * @memberof BeaconState
     */
    finalizedCheckpoint: Ethv1beaconpoolattesterSlashingsAttestation1DataSource;
}
